export const SEQUELIZE = 'SEQUELIZE';
export const DEVELOPMENT = 'development';
export const TEST = 'test';
export const PRODUCTION = 'production';
export const USER_REPOSITORY = 'USER_REPOSITORY';
export const POST_REPOSITORY = 'POST_REPOSITORY';
export const JOB_REPOSITORY = 'JOB_REPOSITORY';
export const ACTIVITY_REPOSITORY = 'ACTIVITY_REPOSITORY';
export const ORDERS_REPOSITORY = 'ORDERS_REPOSITORY';
export const OFFERS_REPOSITORY = 'OFFERS_REPOSITORY';
export const Skills_REPOSITORY = 'Skills_REPOSITORY';
export const USERSKILL_REPOSITORY = 'UserSkill_REPOSITORY';
export const UserEducation_REPOSITORY = 'UserEducation_REPOSITORY';
export const LIKES_REPOSITORY = 'LIKES_REPOSITORY';
export const CONNECTIONS_REPOSITORY = 'CONNECTIONS_REPOSITORY';
export const UNIVERSITIES_REPOSITORY = 'UNIVERSITIES_REPOSITORY';

